// Generated by CoffeeScript 1.9.1
(function() {
  NarLoader.loadFromURL("./mobilemaster.nar").then(function(nanikaDir) {
    return console.log(nanikaDir.getDirectory("shell").files["master/descript.txt"].toString());
  });

}).call(this);

//# sourceMappingURL=tests.js.map
