// Generated by CoffeeScript 1.9.1
(function() {
  NarLoader.loadFromURL("./mobilemaster.nar").then(function(nanikaDir) {
    var descript, str;
    console.log(nanikaDir);
    str = nanikaDir.getDirectory("shell").files["master/descript.txt"].toString();
    descript = NarLoader.Descript.parse(str);
    return console.log(descript);
  });

}).call(this);

//# sourceMappingURL=tests.js.map
