// Generated by CoffeeScript 1.10.0
var Balloon, Blimp, Named, NamedManager, Scope, Shell, Surface, SurfaceRender, SurfaceUtil, b_version, n_version, ref, ref1, ref2, s_version;

ref = require("ikagaka.shell.js"), Shell = ref.Shell, Surface = ref.Surface, SurfaceUtil = ref.SurfaceUtil, SurfaceRender = ref.SurfaceRender, s_version = ref.version;

ref1 = require("ikagaka.balloon.js"), Balloon = ref1.Balloon, Blimp = ref1.Blimp, b_version = ref1.version;

ref2 = require("ikagaka.namedmanager.js"), NamedManager = ref2.NamedManager, Named = ref2.Named, Scope = ref2.Scope, n_version = ref2.version;

exports.versions = {
  Shell: s_version,
  Balloon: b_version,
  NamedManager: n_version
};

exports.Balloon = Balloon;

exports.Blimp = Blimp;

exports.Shell = Shell;

exports.Surface = Surface;

exports.SurfaceUtil = SurfaceUtil;

exports.SurfaceRender = SurfaceRender;

exports.NamedManager = NamedManager;

exports.Named = Named;

exports.Scope = Scope;
