Ikagaka = global["Ikagaka"] || {}
Ikagaka["Shell"] = Ikagaka["Shell"] || {}
Ikagaka["Shell"]["NamedManager"] = NamedManager
Ikagaka["Shell"]["Named"] = Named
Ikagaka["Shell"]["Scope"] = Scope
Ikagaka["Shell"]["Shell"] = Shell
Ikagaka["Shell"]["Surface"] = Surface
Ikagaka["Shell"]["SurfaceUtil"] = SurfaceUtil
Ikagaka["Shell"]["Balloon"] = Balloon
Ikagaka["Shell"]["BalloonSurface"] = BalloonSurface
global["Ikagaka"] = Ikagaka
